name: my_code_view
description: "A widget with side-by-side multi source code view."
version: 0.0.6+1
homepage: "https://github.com/krijk/my_code_view"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.1.0
  selectable: ^0.3.0
  share_plus: ^9.0.0
  string_scanner: ^1.2.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
